"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
var highlight_js_1 = __importDefault(require("highlight.js/lib/highlight.js"));
var cpp_1 = __importDefault(require("highlight.js/lib/languages/cpp"));
var xml_1 = __importDefault(require("highlight.js/lib/languages/xml"));
var awk_1 = __importDefault(require("highlight.js/lib/languages/awk"));
var bash_1 = __importDefault(require("highlight.js/lib/languages/bash"));
var clojure_1 = __importDefault(require("highlight.js/lib/languages/clojure"));
var clojure_repl_1 = __importDefault(require("highlight.js/lib/languages/clojure-repl"));
var cmake_1 = __importDefault(require("highlight.js/lib/languages/cmake"));
var coffeescript_1 = __importDefault(require("highlight.js/lib/languages/coffeescript"));
var crystal_1 = __importDefault(require("highlight.js/lib/languages/crystal"));
var cs_1 = __importDefault(require("highlight.js/lib/languages/cs"));
var csp_1 = __importDefault(require("highlight.js/lib/languages/csp"));
var css_1 = __importDefault(require("highlight.js/lib/languages/css"));
var d_1 = __importDefault(require("highlight.js/lib/languages/d"));
var markdown_1 = __importDefault(require("highlight.js/lib/languages/markdown"));
var dart_1 = __importDefault(require("highlight.js/lib/languages/dart"));
var diff_1 = __importDefault(require("highlight.js/lib/languages/diff"));
var django_1 = __importDefault(require("highlight.js/lib/languages/django"));
var dockerfile_1 = __importDefault(require("highlight.js/lib/languages/dockerfile"));
var elixir_1 = __importDefault(require("highlight.js/lib/languages/elixir"));
var elm_1 = __importDefault(require("highlight.js/lib/languages/elm"));
var ruby_1 = __importDefault(require("highlight.js/lib/languages/ruby"));
var erb_1 = __importDefault(require("highlight.js/lib/languages/erb"));
var erlang_repl_1 = __importDefault(require("highlight.js/lib/languages/erlang-repl"));
var erlang_1 = __importDefault(require("highlight.js/lib/languages/erlang"));
var excel_1 = __importDefault(require("highlight.js/lib/languages/excel"));
var fsharp_1 = __importDefault(require("highlight.js/lib/languages/fsharp"));
var go_1 = __importDefault(require("highlight.js/lib/languages/go"));
var gradle_1 = __importDefault(require("highlight.js/lib/languages/gradle"));
var groovy_1 = __importDefault(require("highlight.js/lib/languages/groovy"));
var handlebars_1 = __importDefault(require("highlight.js/lib/languages/handlebars"));
var haskell_1 = __importDefault(require("highlight.js/lib/languages/haskell"));
var htmlbars_1 = __importDefault(require("highlight.js/lib/languages/htmlbars"));
var http_1 = __importDefault(require("highlight.js/lib/languages/http"));
var ini_1 = __importDefault(require("highlight.js/lib/languages/ini"));
var java_1 = __importDefault(require("highlight.js/lib/languages/java"));
var javascript_1 = __importDefault(require("highlight.js/lib/languages/javascript"));
var json_1 = __importDefault(require("highlight.js/lib/languages/json"));
var julia_1 = __importDefault(require("highlight.js/lib/languages/julia"));
var julia_repl_1 = __importDefault(require("highlight.js/lib/languages/julia-repl"));
var kotlin_1 = __importDefault(require("highlight.js/lib/languages/kotlin"));
var less_1 = __importDefault(require("highlight.js/lib/languages/less"));
var lisp_1 = __importDefault(require("highlight.js/lib/languages/lisp"));
var llvm_1 = __importDefault(require("highlight.js/lib/languages/llvm"));
var lua_1 = __importDefault(require("highlight.js/lib/languages/lua"));
var makefile_1 = __importDefault(require("highlight.js/lib/languages/makefile"));
var mathematica_1 = __importDefault(require("highlight.js/lib/languages/mathematica"));
var matlab_1 = __importDefault(require("highlight.js/lib/languages/matlab"));
var perl_1 = __importDefault(require("highlight.js/lib/languages/perl"));
var nginx_1 = __importDefault(require("highlight.js/lib/languages/nginx"));
var nix_1 = __importDefault(require("highlight.js/lib/languages/nix"));
var objectivec_1 = __importDefault(require("highlight.js/lib/languages/objectivec"));
var ocaml_1 = __importDefault(require("highlight.js/lib/languages/ocaml"));
var pgsql_1 = __importDefault(require("highlight.js/lib/languages/pgsql"));
var php_1 = __importDefault(require("highlight.js/lib/languages/php"));
var plaintext_1 = __importDefault(require("highlight.js/lib/languages/plaintext"));
var powershell_1 = __importDefault(require("highlight.js/lib/languages/powershell"));
var properties_1 = __importDefault(require("highlight.js/lib/languages/properties"));
var protobuf_1 = __importDefault(require("highlight.js/lib/languages/protobuf"));
var puppet_1 = __importDefault(require("highlight.js/lib/languages/puppet"));
var python_1 = __importDefault(require("highlight.js/lib/languages/python"));
var r_1 = __importDefault(require("highlight.js/lib/languages/r"));
var reasonml_1 = __importDefault(require("highlight.js/lib/languages/reasonml"));
var rust_1 = __importDefault(require("highlight.js/lib/languages/rust"));
var scala_1 = __importDefault(require("highlight.js/lib/languages/scala"));
var scheme_1 = __importDefault(require("highlight.js/lib/languages/scheme"));
var scss_1 = __importDefault(require("highlight.js/lib/languages/scss"));
var shell_1 = __importDefault(require("highlight.js/lib/languages/shell"));
var sql_1 = __importDefault(require("highlight.js/lib/languages/sql"));
var stylus_1 = __importDefault(require("highlight.js/lib/languages/stylus"));
var swift_1 = __importDefault(require("highlight.js/lib/languages/swift"));
var yaml_1 = __importDefault(require("highlight.js/lib/languages/yaml"));
var tex_1 = __importDefault(require("highlight.js/lib/languages/tex"));
var typescript_1 = __importDefault(require("highlight.js/lib/languages/typescript"));
var vim_1 = __importDefault(require("highlight.js/lib/languages/vim"));
highlight_js_1.default.registerLanguage('cpp', cpp_1.default);
highlight_js_1.default.registerLanguage('xml', xml_1.default);
highlight_js_1.default.registerLanguage('awk', awk_1.default);
highlight_js_1.default.registerLanguage('bash', bash_1.default);
highlight_js_1.default.registerLanguage('clojure', clojure_1.default);
highlight_js_1.default.registerLanguage('clojure-repl', clojure_repl_1.default);
highlight_js_1.default.registerLanguage('cmake', cmake_1.default);
highlight_js_1.default.registerLanguage('coffeescript', coffeescript_1.default);
highlight_js_1.default.registerLanguage('crystal', crystal_1.default);
highlight_js_1.default.registerLanguage('cs', cs_1.default);
highlight_js_1.default.registerLanguage('csp', csp_1.default);
highlight_js_1.default.registerLanguage('css', css_1.default);
highlight_js_1.default.registerLanguage('d', d_1.default);
highlight_js_1.default.registerLanguage('markdown', markdown_1.default);
highlight_js_1.default.registerLanguage('dart', dart_1.default);
highlight_js_1.default.registerLanguage('diff', diff_1.default);
highlight_js_1.default.registerLanguage('django', django_1.default);
highlight_js_1.default.registerLanguage('dockerfile', dockerfile_1.default);
highlight_js_1.default.registerLanguage('elixir', elixir_1.default);
highlight_js_1.default.registerLanguage('elm', elm_1.default);
highlight_js_1.default.registerLanguage('ruby', ruby_1.default);
highlight_js_1.default.registerLanguage('erb', erb_1.default);
highlight_js_1.default.registerLanguage('erlang-repl', erlang_repl_1.default);
highlight_js_1.default.registerLanguage('erlang', erlang_1.default);
highlight_js_1.default.registerLanguage('excel', excel_1.default);
highlight_js_1.default.registerLanguage('fsharp', fsharp_1.default);
highlight_js_1.default.registerLanguage('go', go_1.default);
highlight_js_1.default.registerLanguage('gradle', gradle_1.default);
highlight_js_1.default.registerLanguage('groovy', groovy_1.default);
highlight_js_1.default.registerLanguage('handlebars', handlebars_1.default);
highlight_js_1.default.registerLanguage('haskell', haskell_1.default);
highlight_js_1.default.registerLanguage('htmlbars', htmlbars_1.default);
highlight_js_1.default.registerLanguage('http', http_1.default);
highlight_js_1.default.registerLanguage('ini', ini_1.default);
highlight_js_1.default.registerLanguage('java', java_1.default);
highlight_js_1.default.registerLanguage('javascript', javascript_1.default);
highlight_js_1.default.registerLanguage('json', json_1.default);
highlight_js_1.default.registerLanguage('julia', julia_1.default);
highlight_js_1.default.registerLanguage('julia-repl', julia_repl_1.default);
highlight_js_1.default.registerLanguage('kotlin', kotlin_1.default);
highlight_js_1.default.registerLanguage('less', less_1.default);
highlight_js_1.default.registerLanguage('lisp', lisp_1.default);
highlight_js_1.default.registerLanguage('llvm', llvm_1.default);
highlight_js_1.default.registerLanguage('lua', lua_1.default);
highlight_js_1.default.registerLanguage('makefile', makefile_1.default);
highlight_js_1.default.registerLanguage('mathematica', mathematica_1.default);
highlight_js_1.default.registerLanguage('matlab', matlab_1.default);
highlight_js_1.default.registerLanguage('perl', perl_1.default);
highlight_js_1.default.registerLanguage('nginx', nginx_1.default);
highlight_js_1.default.registerLanguage('nix', nix_1.default);
highlight_js_1.default.registerLanguage('objectivec', objectivec_1.default);
highlight_js_1.default.registerLanguage('ocaml', ocaml_1.default);
highlight_js_1.default.registerLanguage('pgsql', pgsql_1.default);
highlight_js_1.default.registerLanguage('php', php_1.default);
highlight_js_1.default.registerLanguage('plaintext', plaintext_1.default);
highlight_js_1.default.registerLanguage('powershell', powershell_1.default);
highlight_js_1.default.registerLanguage('properties', properties_1.default);
highlight_js_1.default.registerLanguage('protobuf', protobuf_1.default);
highlight_js_1.default.registerLanguage('puppet', puppet_1.default);
highlight_js_1.default.registerLanguage('python', python_1.default);
highlight_js_1.default.registerLanguage('r', r_1.default);
highlight_js_1.default.registerLanguage('reasonml', reasonml_1.default);
highlight_js_1.default.registerLanguage('rust', rust_1.default);
highlight_js_1.default.registerLanguage('scala', scala_1.default);
highlight_js_1.default.registerLanguage('scheme', scheme_1.default);
highlight_js_1.default.registerLanguage('scss', scss_1.default);
highlight_js_1.default.registerLanguage('shell', shell_1.default);
highlight_js_1.default.registerLanguage('sql', sql_1.default);
highlight_js_1.default.registerLanguage('stylus', stylus_1.default);
highlight_js_1.default.registerLanguage('swift', swift_1.default);
highlight_js_1.default.registerLanguage('yaml', yaml_1.default);
highlight_js_1.default.registerLanguage('tex', tex_1.default);
highlight_js_1.default.registerLanguage('typescript', typescript_1.default);
highlight_js_1.default.registerLanguage('vim', vim_1.default);
exports.hljs = highlight_js_1.default;
//# sourceMappingURL=highlight.js-slim.js.map